// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/3/2026, 3:38:05 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/chenning/personalProjects/backend/music-story/apps/web-client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/plugins/**/*.{js,ts,mjs}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/composables/**/*.{js,ts,mjs}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/utils/**/*.{js,ts,mjs}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/chenning/personalProjects/backend/music-story/apps/web-client/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;